spring:
  application:
    name: collector

grpc:
  server:
    port: 59091

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
    topics:
      sensor-events: telemetry.sensors.v1
      hubs-events:   telemetry.hubs.v1

logging:
  level:
    ru.yandex.practicum: TRACE
    org.springframework: ERROR
    org.apache.kafka:   WARN
